// 从 参考/replica-prompt.md 生成 src/composables/geom3dPrompt.ts（改提示词请改 md 再跑这个）

const fs = require('fs');
const md = fs.readFileSync('参考/replica-prompt.md', 'utf8');
const ts = '/** 「三维立体图」的配套提示词 + 常用预设。\n'
  + ' *\n'
  + ' *  这份 JSON 从哪来：app 自己不会生成它 —— 它是**让大模型把题目翻译成三维描述**的产物。\n'
  + ' *  所以弹窗里给了「复制提示词」按钮：把它连同题目（文字或题图）一起发给任意 AI，\n'
  + ' *  拿回来的 JSON 粘进弹窗即可。常用几何体则直接用下面的预设，不必每次都问 AI。\n'
  + ' *\n'
  + ' *  提示词正文来自 `参考/replica-prompt.md`（用户给的那份），生成脚本写在\n'
  + ' *  `tools/solidfit/gen-prompt.cjs` —— 改提示词请改那个 md，再重新生成。\n'
  + ' */\n\n'
  + 'export const GEOM3D_PROMPT = ' + JSON.stringify(md) + '\n\n'
  + 'export interface Geom3DPreset { name: string; json: string }\n\n'
  + 'const P = (v: Record<string, [number, number, number]>, faces: string[][], extra: Record<string, unknown> = {}) =>\n'
  + '  JSON.stringify({ vertices: v, faces, ...extra }, null, 1)\n\n'
  + 'export const GEOM3D_PRESETS: Geom3DPreset[] = [\n'
  + '  {\n'
  + '    name: \'正方体 ABCD-A₁B₁C₁D₁\',\n'
  + '    json: P({\n'
  + '      A: [0, 0, 0], B: [2, 0, 0], C: [2, 2, 0], D: [0, 2, 0],\n'
  + '      A1: [0, 0, 2], B1: [2, 0, 2], C1: [2, 2, 2], D1: [0, 2, 2],\n'
  + '    }, [[\'A\', \'B\', \'C\', \'D\'], [\'A1\', \'B1\', \'C1\', \'D1\'], [\'A\', \'B\', \'B1\', \'A1\'], [\'B\', \'C\', \'C1\', \'B1\'], [\'C\', \'D\', \'D1\', \'C1\'], [\'D\', \'A\', \'A1\', \'D1\']],\n'
  + '      { view: { azim: -35, elev: 20 } }),\n'
  + '  },\n'
  + '  {\n'
  + '    name: \'长方体 2×1.2×1.6\',\n'
  + '    json: P({\n'
  + '      A: [0, 0, 0], B: [2, 0, 0], C: [2, 1.2, 0], D: [0, 1.2, 0],\n'
  + '      A1: [0, 0, 1.6], B1: [2, 0, 1.6], C1: [2, 1.2, 1.6], D1: [0, 1.2, 1.6],\n'
  + '    }, [[\'A\', \'B\', \'C\', \'D\'], [\'A1\', \'B1\', \'C1\', \'D1\'], [\'A\', \'B\', \'B1\', \'A1\'], [\'B\', \'C\', \'C1\', \'B1\'], [\'C\', \'D\', \'D1\', \'C1\'], [\'D\', \'A\', \'A1\', \'D1\']],\n'
  + '      { view: { azim: -35, elev: 18 } }),\n'
  + '  },\n'
  + '  {\n'
  + '    name: \'正三棱柱 ABC-A₁B₁C₁\',\n'
  + '    json: P({\n'
  + '      A: [0, 0, 0], B: [2.4, 0, 0], C: [1.2, 2.078, 0],\n'
  + '      A1: [0, 0, 2], B1: [2.4, 0, 2], C1: [1.2, 2.078, 2],\n'
  + '    }, [[\'A\', \'B\', \'C\'], [\'A1\', \'B1\', \'C1\'], [\'A\', \'B\', \'B1\', \'A1\'], [\'B\', \'C\', \'C1\', \'B1\'], [\'C\', \'A\', \'A1\', \'C1\']],\n'
  + '      { view: { azim: -35, elev: 18 } }),\n'
  + '  },\n'
  + '  {\n'
  + '    name: \'正四棱锥 P-ABCD（含高 PO）\',\n'
  + '    json: P({\n'
  + '      A: [0, 0, 0], B: [2, 0, 0], C: [2, 2, 0], D: [0, 2, 0], O: [1, 1, 0], P: [1, 1, 3],\n'
  + '    }, [[\'A\', \'B\', \'C\', \'D\'], [\'P\', \'A\', \'B\'], [\'P\', \'B\', \'C\'], [\'P\', \'C\', \'D\'], [\'P\', \'D\', \'A\']],\n'
  + '      { auxiliary: [{ from: \'P\', to: \'O\' }], view: { azim: -35, elev: 20 } }),\n'
  + '  },\n'
  + '  {\n'
  + '    name: \'正四棱柱 + 四条竖棱中点 + C₂ 连线\',\n'
  + '    json: P({\n'
  + '      A: [0, 0, 0], B: [2, 0, 0], C: [2, 2, 0], D: [0, 2, 0],\n'
  + '      A1: [0, 0, 2], B1: [2, 0, 2], C1: [2, 2, 2], D1: [0, 2, 2],\n'
  + '      A2: [0, 0, 1], B2: [2, 0, 1], C2: [2, 2, 1], D2: [0, 2, 1],\n'
  + '    }, [[\'A\', \'B\', \'C\', \'D\'], [\'A1\', \'B1\', \'C1\', \'D1\'], [\'A\', \'B\', \'B1\', \'A1\'], [\'B\', \'C\', \'C1\', \'B1\'], [\'C\', \'D\', \'D1\', \'C1\'], [\'D\', \'A\', \'A1\', \'D1\']],\n'
  + '      { auxiliary: [{ from: \'C2\', to: \'A2\' }, { from: \'C2\', to: \'B2\' }, { from: \'C2\', to: \'D2\' }], view: { azim: -35, elev: 20 } }),\n'
  + '  },\n'
  + ']\n';
fs.writeFileSync('src/composables/geom3dPrompt.ts', ts);
fs.writeFileSync('tools/solidfit/gen-prompt.cjs', '// 从 参考/replica-prompt.md 生成 src/composables/geom3dPrompt.ts（改提示词请改 md 再跑这个）\n' + fs.readFileSync('.probe/genp.cjs', 'utf8'));
console.log('生成 src/composables/geom3dPrompt.ts：' + ts.length + ' 字符');
